spring:
  datasource:
    url: jdbc:postgresql://ep-empty-dust-ad3ylf2u-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_mNZkze8fOd2t
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

mercado_pago_sample_access_token: APP_USR-3233389305480692-071210-80df6976d0781525aea7b4a41af33037-2535936225
